name: Murmur
options:
  bundleIdPrefix: com.murmur
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  Murmur:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
          - "*.xcworkspace"
          - Scripts
          - Resources
          - Server
          - build
          - "*.zip"
          - "*.app"
      - path: Resources/VoiceSamples
        type: folder
      - path: Resources/Python
        type: folder
      - path: Server
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.murmur.app
        PRODUCT_NAME: Murmur
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: Murmur.entitlements
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: Murmur.entitlements
