name: Murmur
options:
  bundleIdPrefix: com.murmur
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

# Swift Package Dependencies for Native TTS
packages:
  mlx-audio:
    url: https://github.com/Blaizzy/mlx-audio
    branch: main
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift
    from: "0.30.2"

targets:
  Murmur:
    type: application
    platform: macOS
    dependencies:
      - package: mlx-audio
        product: MLXAudio
      - package: mlx-swift
        product: MLXFast
      - package: mlx-swift
        product: MLXRandom
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
          - "*.xcworkspace"
          - Scripts
          - Resources
          - Server
          - build
          - "*.zip"
          - "*.app"
          - Info.plist
          - MIGRATION_PLAN.md
          - repomix-output.xml
      - path: Resources/VoiceSamples
        type: folder
      # Kokoro voice data files (JSON) for native TTS - must be at root level for Bundle.main.path()
      - path: Resources
        includes:
          - "*.json"
        buildPhase: resources
      # Kokoro model weights for native TTS
      - path: Resources/KokoroModel
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.murmur.app
        PRODUCT_NAME: Murmur
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: Murmur.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        DEVELOPMENT_TEAM: 2M3JKYS79P
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "Developer ID Application"
    entitlements:
      path: Murmur.entitlements
